In [2]:
# NUMPY

In [3]:
import numpy as np

In [4]:
#Arrays and basic functions

list = [0,1,2,3,4]
array = np.array(list)
array

array([0, 1, 2, 3, 4])

In [6]:
np.arange(0,10)
#(beginning with, up to but not including, optional step size)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [8]:
np.zeros(shape=(5,5))
#(rows, columns)
#defaults to floats(arange defaunts to int) 

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones(shape=(2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.ones((2,4))
#shorter notation

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
np.random.seed(101)
# creates the same random numbers each time
array = np.random.randint(0,100,10)
#from zero to 100 give me 10 instances
array

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [21]:
array2 = np.random.randint(0,100,10)
array2


array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40])

In [23]:
array.max()
#max value in an array

95

In [24]:
array.argmax()
#find its location

0

In [25]:
array.mean()

60.8

In [26]:
#reshaping
array.reshape((2,5))
#this will not work if the row/column dimensions do not equal to original instance sum

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

In [33]:
matrix = np.arange(0,100).reshape(10,10)

In [34]:
matrix

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [35]:
matrix.shape

(10, 10)

In [37]:
#find an individual instance through slicing

row = 0
col = 1

matrix[row,col]



1

In [38]:
#slice number 35

matrix[3,5]

35

In [39]:
#obtain a portion of an array
#all columns in first column
matrix[:,1]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [40]:
#reshape
matrix[:,1].reshape(10,1)

array([[ 1],
       [11],
       [21],
       [31],
       [41],
       [51],
       [61],
       [71],
       [81],
       [91]])

In [41]:
matrix[2,:]

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [42]:
#slice rows and colums
matrix[0:3,0:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [45]:
#copy matrix into new variable and replace instances in a slice

new_matrix = matrix.copy()
new_matrix

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [46]:
new_matrix[0:6,:] = 77

In [47]:
new_matrix

array([[77, 77, 77, 77, 77, 77, 77, 77, 77, 77],
       [77, 77, 77, 77, 77, 77, 77, 77, 77, 77],
       [77, 77, 77, 77, 77, 77, 77, 77, 77, 77],
       [77, 77, 77, 77, 77, 77, 77, 77, 77, 77],
       [77, 77, 77, 77, 77, 77, 77, 77, 77, 77],
       [77, 77, 77, 77, 77, 77, 77, 77, 77, 77],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])